### ISSUE TITLE
"Running the SpliceLauncher tests" with Error

### ISSUE THREAD

**Issue by JulieBlasquiz** [raphaelleman/SpliceLauncher#11]
Hi,

After following the readme instructions for installing the tool and passing the "Configure SpliceLauncher with INSTALL mode" step with the message "finished successfully", the "Running the SpliceLauncher tests" step ends with an error : 

###############################################
###############################################

Will run SpliceLauncher
cmd = Rscript /.../conda/envs/spliceLauncher/SpliceLauncher/scripts/SpliceLauncherAnalyse.r --input /.../conda/envs/spliceLauncher/SpliceLauncher/testSpliceLauncher/testSpliceLauncher.txt -O /.../conda/envs/spliceLauncher/SpliceLauncher/testSpliceLauncher --RefSeqAnnot /.../conda/envs/spliceLauncher/SpliceLauncher/refSpliceLauncher/SpliceLauncherAnnot.txt -n 10 --threshold 1
Warning message:
package 'WriteXLS' was built under R version 4.3.2
SpliceLauncherV2
######################
#Parameters of SpliceLauncher
######################
Matrix count: /.../conda/envs/spliceLauncher/SpliceLauncher/testSpliceLauncher/testSpliceLauncher.txt
Output directory: /.../conda/envs/spliceLauncher/SpliceLauncher/testSpliceLauncher
Run name: testSpliceLauncher
Sample Name:
RefSeq Annot: /.../conda/envs/spliceLauncher/SpliceLauncher/refSpliceLauncher/SpliceLauncherAnnot.txt
Output format: excel
List of transcripts:
Remove the other genes: NO
BED annotation: NO
Display graphics: NO
Threshold: 1
nb intervals for Neg Binom: 10
######################
#Data formating...
######################
   Import matrix count...
   Download RefSeq File...
   Get gene name...
   I don't find 7 transcrit(s) ( NM_000059, NM_001136571, NM_007297, NM_007300, NM_023037, NM_032387, NR_027676 )
   Merge transcrit...
0
Warning message:
In max(x) : no non-missing arguments to max; returning -Inf
Error in data.frame(Gene = names(TransMaj), NMadjust = TransMaj, row.names = 1:length(TransMaj)) :
  row names supplied are of the wrong length
Execution halted

We download Fasta genome and GFF annotation file from RefSeq at this url : 

https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/GRCh37_latest_genomic.fna.gz
https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/GRCh37_latest_genomic.gff.gz

Thanks
Julie

**Comment by raphaelleman** [comment]
Bug fix in the version 3
