### ISSUE TITLE
Singularity image not working

### ISSUE THREAD

**Issue by camillebenoist** [raphaelleman/SpliceLauncher#3]
Hi,

I tried to use the singularity image to run SpliceLauncher, but I found some git merging issue still present in SpliceLauncherAnalyse.r (line 1):

<<<<<<< HEAD:scripts/SpliceLauncherAnalyse.r

So I am not sure what to do with the singularity image, they are maybe other scripts not up to date ? Is there any way to make it work?

Thank you,

Camille

**Comment by raphaelleman** [comment]
Hi 

First of all, I apology for the very long delay of my answer.
Second of all, I just update the dockerfile toward singularity recipe. Now you can build the environment of SpliceLauncher with singularity.

Best regrds
