### ISSUE TITLE
Error on Generate BED annotation step

### ISSUE THREAD

**Issue by neel404** [raphaelleman/SpliceLauncher#4]
Hi,

I am trying to Configure the SpliceLauncher environment and getting the below error on Generate BED annotation. Could you please help to fix it?

bash ./SpliceLauncher.sh --runMode INSTALL     -O ./refSpliceLauncher     --STAR STAR     --samtools samtools     --bedtools bedtools     --gff genome/Iaq6.scaffolds.sorted.gff     --fasta genome/Iaq6.scaffolds.fna -t 40
###############################################
###############################################

Parsing configuration file...
/home/kcgeb/kcjith/SpliceLauncher/config.cfg OK.

runMode INSTALL
INSTALL: TRUE
samtools OK.
bedtools OK.
STAR OK.
Rscript OK.
perl OK.
Parsing OK.
###############################################
###############################################

fasta_path = /home/kcgeb/kcjith/SpliceLauncher/genome/Iaq6.scaffolds.fna
gff_path = /home/kcgeb/kcjith/SpliceLauncher/genome/Iaq6.scaffolds.sorted.gff
Will run generateSpliceLauncherDB.
Rscript /home/kcgeb/kcjith/SpliceLauncher/scripts/generateSpliceLauncherDB.r -i /home/kcgeb/kcjith/SpliceLauncher/genome/Iaq6.scaffolds.sorted.gff -o /home/kcgeb/kcjith/SpliceLauncher/refSpliceLauncher
Read GFF file ...
Remove meta-header ...
Format GFF file ...
Warning message:
In matrix(splitRaw, ncol = nCol, byrow = TRUE) :
  data length [6837676] is not a sub-multiple or multiple of the number of rows [759742]
Change chr annotation ...
Extract exon coordinates ...
Extract exon annotation ...
Merge exon files ...
Extract CDS coordinates ...
Extract CDS annotation ...
Merge CDS files ...
Generate BED annotation ...
Error in data.frame(V1 = exonCoord$chr, V2 = as.numeric(exonCoord$start) -  :
  arguments imply differing number of rows: 0, 1
Calls: getBEDfile -> data.frame
Execution halted

**Comment by raphaelleman** [comment]
sorry but SpliceLauncher was not design to work with other genomes than the human genome.
