### ISSUE TITLE
Singularity image build fails

### ISSUE THREAD

**Issue by maressyl** [raphaelleman/SpliceLauncher#7]
Hi,

I am trying to build the Singularity image to use SpliceLauncher on our servers, but it seems the Singularity recipe attempts to download https://github.com/samtools/samtools/releases/1.12/samtools-1.12.tar.bz2 which is currently dead.

Best regards,
Sylvain

**Comment by raphaelleman** [comment]
Sorry the long delay of my answer, it seems that my email alert does not work anymore.
I have just pushed the correction
