### ISSUE TITLE
Singularity recipe needs a slight update

### ISSUE THREAD

**Issue by vidboda** [raphaelleman/SpliceLauncher#8]
Hi,

to successfully build the singularity container, I've had to update the samtools URL, line 70 of splicelauncher.recipe becoming:

```
wget --no-check-certificate -O samtools.tar.bz2 "https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2"
```

(current is:

```
wget --no-check-certificate -O samtools.tar.bz2 "https://github.com/samtools/samtools/releases/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2"
```
)

=> added 'download/' after 'releases/'

**Comment by raphaelleman** [comment]
Sorry the long delay of my answer, it seems that my email alert does not work anymore.
I have just pushed the correction
