### ISSUE TITLE
SpliceLauncher test fails with singularity image

### ISSUE THREAD

**Issue by vidboda** [raphaelleman/SpliceLauncher#9]
Hi,

I'm currently unsuccessfully trying to launch tests on the SpliceLaunhcer singularity container.

My config.cfg file is the following:

```
# This file should contain all the necessary path and filename
# to run SpliceLauncher


## Software path
# for a soft in your PATH, you could let the binary name, not the complete and absolute path
# eg.: you could use samtools
samtools="samtools"
bedtools="bedtools"
STAR="STAR"
Rscript="Rscript" # Rscript or /path/to/Rscript
perl="perl" # perl or /path/to/perl

## data localization
genome="/RS_IURC/data/MobiDL/Datasets/STAR/150pb/"
gff="/RS_IURC/data/MobiDL/Datasets/splicelauncher/GRCh37_latest_genomic.sub.gff"

## output from generateSpliceLauncherDB.r script
SJDBannot=
spliceLaucherAnnot=
BEDrefPath=

##
```

In this case I do not define any BEDrefPath, I've got the following error during the counting step:

```
###############################################
####### Launch counting step
###############################################

bam_path = /softs/SpliceLauncher/testSpliceLauncher/Bam
Will run counting.
cmd = /usr/local/SpliceLauncher/SpliceLauncher/scripts/pipelineRNAseq.sh --runMode Count -B /softs/SpliceLauncher/testSpliceLauncher/Bam -O /softs/SpliceLauncher/testSpliceLauncher --bedannot  --bedtools bedtools --perlscript /usr/local/SpliceLauncher/SpliceLauncher/scripts --samtools samtools 
readlink: unrecognized option '--bedtools'
```

Then I tried to comment the BEDrefPath line in the config file which gave me the following error:

```
cmd = /usr/local/SpliceLauncher/SpliceLauncher/scripts/pipelineRNAseq.sh --runMode Count -B /softs/SpliceLauncher/testSpliceLauncher/Bam -O /softs/SpliceLauncher/testSpliceLauncher --bedannot /usr/local/SpliceLauncher/SpliceLauncher/refData/refExons.bed --bedtools bedtools --perlscript /usr/local/
SpliceLauncher/SpliceLauncher/scripts --samtools samtools 
readlink: /usr/local/SpliceLauncher/SpliceLauncher/refData/refExons.bed: No such file or directory
```

I checked the Singularity image and indeed the file /usr/local/SpliceLauncher/SpliceLauncher/refData/refExons.bed does not exist (nor the refData folder).

This file is mentioned as optional in the README. It is not also clear to me what the "SJDBannot" and "spliceLaucherAnnot" (possible typo) variables form the config.cfg file should be set to.

Thanks in advance,
david

**Comment by raphaelleman** [comment]
The files SJDBannot, spliceLaucherAnnot and BEDrefPath are supposed to be generated during the configuration step of SpliceLauncher. 
You can create your own config.cfg by the following commands:
1 - Start from initial config.cfg file
`wget --no-check-certificate -O <MyConfig>.cfg https://github.com/raphaelleman/SpliceLauncher/blob/master/config.cfg`
2 - Launch install mode of SpliceLauncher
`mkdir ./refSpliceLauncher # Here this folder will contain the reference files used by SpliceLauncher
bash ./SpliceLauncher.sh --runMode INSTALL \
    --config /path/to/<MyConfig>.cfg \ # All ref file path will be writen in this config file
    -O ./refSpliceLauncher \
    --STAR /path/to/STAR \ # No need if tool already present in the singularity image
    --samtools /path/to/samtools \ # No need if tool already present in the singularity image
    --bedtools /path/to/bedtools \ # No need if tool already present in the singularity image
    --gff /path/to/gff \
    --fasta /path/to/fasta`
3 - At each running of SpliceLauncher, precise your config file
`bash ./SpliceLauncher.sh --runMode Align,Count,SpliceLauncher  --config /path/to/<MyConfig>.cfg -F ./dataTest/fastq/ -O ./testSpliceLauncher/ `

**Comment by vidboda** [comment]
thanks, the test ran just fine after rerunning the INSTALL mode
